1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [7]:
import numpy as np

zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

# элементарные действия
#mult_lists= [x * y for x, y in zip(zp, ks)]
C = np.mean(zp * ks) - np.mean(zp)*np.mean(ks)
print(f'Ковариация: {C}')

# ковариация с помощью cov из  numpy
C = np.cov(zp, ks, ddof = 0)
print('ковариация с помощью cov из numpy: ')
print(C)

#коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков
sigma_zp = np.std(zp, ddof = 0)
sigma_ks = np.std(ks, ddof = 0)

r_zp_ks = C / (sigma_zp * sigma_ks)
print('Коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков:')
print(r_zp_ks)

# Коэффициент корреляции с помощью numpy
r = np.corrcoef(zp, ks)
print('Коэффициент корреляции с помощью numpy')
print(r)

Ковариация: 9157.839999999997
ковариация с помощью cov из numpy: 
[[ 3494.64  9157.84]
 [ 9157.84 30468.89]]
Коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков:
[[0.33866702 0.88749009]
 [0.88749009 2.95275283]]
Коэффициент корреляции с помощью numpy
[[1.         0.88749009]
 [0.88749009 1.        ]]


2.Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [16]:
import math

IQ =np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
alfa = 0.05


n= len(IQ)

X_ = np.mean(IQ)
# из таблицы Стьюдента v = n -1  и alfa = 0.05/2
sigma = 2.262 

T_1 = X_ - (sigma*np.std(IQ, ddof=1))/math.sqrt(n)
T_2 = X_ + (sigma*np.std(IQ, ddof=1))/math.sqrt(n)

print(f'Доверительный интервал равен от {T_1} до {T_2}')

Доверительный интервал равен от 110.55660776308164 до 125.64339223691834


3. Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [17]:
std = 5
n = 27
X_ = 174.2
alfa = 0.05

# из таблицы Z  распределения
Z_a = 1.96

Z_1 = X_ - Z_a * std/math.sqrt(n)
Z_2 = X_ + Z_a * std/math.sqrt(n)

print(f'Дверительный интервал равен от {Z_1} до {Z_2}')

Дверительный интервал равен от 172.31398912064722 до 176.08601087935276
